spring.application.name=idouaksim-halima-Exam-JEE

# H2 Database
spring.datasource.url=jdbc:h2:mem:assurancedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inheritance strategy (JOINED)
spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop

# JWT
app.jwt.secret=enset-exam-jee-secret-key-2024-very-long-for-hs512-algorithm-minimum-512bits-required
app.jwt.expiration=86400000

# Springdoc
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method

# Server
server.port=8080
